### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#14]
How modular should the customization be?

Being able to pair any wheel with any frame would be cool but is that too limiting for more wildly designed unicycles that might not fit the normal proportions?

some examples unicycles that could mix and match parts
![image](https://user-images.githubusercontent.com/11905265/146607362-35859dd8-24a9-42bf-b4a1-5080dff79ef1.png)

weird unicycles
![image](https://user-images.githubusercontent.com/11905265/146607766-918ddd68-1a1f-4ac6-9f62-715df460d1fb.png)

**Comment by cr4yz** [comment]
I wonder if we can have it both ways.  The weird unicycles might have little to no customization, maybe even come as a complete build and sorta be a special thing, and the standard unicycle could have tons of interchangeable parts

**Comment by youhavehowie** [comment]
Yea it could work both ways but the weird unicycles would also take a lot of extra work in terms of animation and if we do gloat/emote animations would we be limited since they have to work on every unicycle form factor

**Comment by youhavehowie** [comment]
dumping some more art/ideas in here to keep it in one spot
![image](https://user-images.githubusercontent.com/11905265/163621129-b85815f5-690b-49ad-aa28-25e31fc99a47.png)
![image](https://user-images.githubusercontent.com/11905265/163621227-2a630c91-f18f-4e70-82e2-8276ffda3f74.png)

![image](https://user-images.githubusercontent.com/11905265/163621366-7a97275d-2112-4f5b-8258-a05cf73bbcb4.png)
![image](https://user-images.githubusercontent.com/11905265/163621389-6caca126-763c-451e-8579-57754b600bd7.png)
