### ISSUE TITLE
Breakables and moving platforms

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-unicycle-frenzy#18]
The main challenge here is creating these in a way that works per-client.  i.e. a plank that breaks when a player rolls over it, we want the plank to break for every player, not just the first player to reach it.

- [ ] Breakables
- [x] Moving platforms
- [ ] Per-client
  - [ ] Restore to original state when run is restarted

**Comment by youhavehowie** [comment]
I think the per-client stuff can be put on the back burner until it becomes more of an issue, thinking about this more I think it's going to be more jarring and seem like a bug seeing players floating in mid-air. It does introduce some potentially annoying RNG for speed runs but so far no one has complained and I think its more fun watching other players fall while everyone is synced up
