### ISSUE TITLE
adjust collision volume size for unicycle/player

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#21]
I assume these two issues are because of the player's collision volume

some weird behavior on this section of Pop Rock
https://files.facepunch.com/howie/1b0411b1/s%26box%202022-01-04%2014-30-34.mp4

floating just beyond edges
![image](https://user-images.githubusercontent.com/11905265/148113848-5d4259d8-24bf-4458-b4d1-e16699d64f2e.png)

Also, can we add a collision for the player's body as well so they don't end up clipping like this? I think the body collider should be slightly smaller than the character's actual body though to allow for a little forgiveness. If the body collider hits any objects it should cause the player to fall
![image](https://user-images.githubusercontent.com/11905265/148114545-47fb014f-3600-4da6-a290-eabd40e70ff6.png)

**Comment by cr4yz** [comment]
Added!  There _may_ be some edge cases with these changes, lemme know if you find anything.
