### ISSUE TITLE
Completing the Vertical Slice

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#32]
Wanted to outline what I think would be a good way to wrap the game mode up for the time being until we get more players into s&box and it looks like its worth developing further

- **7 solid maps(not finished art just block ins)**
    Hop Stop(maybe needs to be longer?)
    Pop Rock
    Splinter
    Bookworm
    Wooden Gaps(needs a rework)
    Beach(needs a rework or maybe a replacement)
    Flow(open to replacing it with something else)

- **Battle pass, cosmetic unlocks, and XP**
    we have 50 cosmetic items currently, take away 5 for the default stuff and we have 45 cosmetic unlocks so far... let's make 5 more to get an even 50
    
    The battle pass goes up to level 100
    every 2 levels progressed unlocks a cosmetic(50 unlocks total)
    players level up every 10xp points

- **Ways to get xp**
  Medals:
  gold = 50xp  = 350 total xp
  silver = 40xp = 280 total xp
  bronze = 30xp = 210 total xp
  
  Playing:
  playing for a 1/2 hour = 5xp (allows players who are still learning to progress and players can still earn xp on community maps)

  Other:
  Completing a course once = 50 xp
  we discussed some other achievements like collecting challenges which I think would be good too, because a lot of people will probably give up early if the medals are the only meaningful way to progress. 

  840 total xp points possible to earn through medals, the rest of the xp is earned by just playing and completing maps. Players will likely not need to get every medal before they reach the end of the battle pass

- **Animations**
  A base set of animations I think will be pretty crucial for giving players feedback about how they're controlling their character so its more than just visual polish

- **Tutorial Map**
  A tutorial map to help new players along with a prompt when they load up the game for the first time to load into the tutorial map

Open to any suggestions, I feel like this would give a nice vertical slice and anyone new to sbox would be able to have fun with it right away. Was also thinking about doing a tutorial level, not sure how we would encourage new players to load it up though

**Comment by cr4yz** [comment]
I'm happy with that, an experience system will give a nice sense of progression rounding things out.

Would it be worth building up some type of analytics system, i.e.:
 - see how much progress players have made in a map
 - did they leave before ever finishing the map
 - heatmaps for where people fall or quit game
 - who's grinding individual maps for world records
 - how many people have acquired x achievement

This data would help us get a better idea of what works and what doesn't.

For the tutorial level maybe we could prompt new players to switch to the tutorial map when they first make a game?  We could do hints outside the tutorial map too, like if a player is leaning too far have pop up by terry's head saying straighten out with WASD.

**Comment by youhavehowie** [comment]
The analytics stuff would be super helpful for designing new maps and adjusting the current ones but hard to say if it's worth doing now or later. I've been able to make a fair amount of map adjustments just based on playing with other people so far and with the small size of the current player base I don't know how much value we'd get from it atm. That being said, I can imagine analytics being really useful for a lot of these obstacle course challenge type game modes like mini-golf too, I don't if it's possible to make something generic enough that any game mode could potentially implement it though.

Can we have that tutorial suggestion window show for either creating their own game or joining a game for the first time? I worry the hints will be more annoying than helpful for most players and they'll just want to turn it off as soon as they can but those kinds of contextual hints on the tutorial map would be great.

added animation to the list
