### ISSUE TITLE
Tilting to extreme slopes

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#35]
When I roll my character at an almost parallel angle over an edge with a really steep angled plane on the other side my character awkwardly tilts to meet the extreme angle
 https://files.facepunch.com/howie/1b1111b1/s%26box%202022-02-11%2011-29-08.mp4

I thought maybe adjusting the groundAngle > 3f here to be higher would help fix it but it doesn't seem to have an effect
```
if ( GroundEntity != null && groundAngle > 3f )
		{
			var groundRot = FromToRotation( Vector3.Up, !NoTilt ? GroundNormal : Vector3.Up );
			groundRot *= pl.TargetForward;
			var groundTilt = groundRot.Angles().WithYaw( 0 );
			var tiltAlpha = Easing.EaseIn( groundAngle / 30f );

			tilt += groundTilt * tiltAlpha * SlopeTipSpeed * Time.Delta;
		}
```
first noticed the behavior on uf_beach with this angled plank
![image](https://user-images.githubusercontent.com/11905265/153632444-33aac5dc-d456-4a8a-87b0-0ca707503fa2.png)

I think it still does do it when going straight off the edge too, but it's a lot harder to make happen and less noticeable. I think ideally the tilt angle would stay the same and the character would just slide down extreme slopes like that

**Comment by cr4yz** [comment]
I've set it to not tilt on steep slopes, looks to behave well on playground.  Lemme know if you find any issues!

**Comment by youhavehowie** [comment]
much better, thank you!
