### ISSUE TITLE
Controller Improvements

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#36]
Here's what I think the default controller layout should be:

```
Right Trigger = pedal right
Left Trigger = pedal left

Right Bumper = jump
Left Bumper = brake

Right joystick = camera movement
Left joystick = lean

Top face button(Y on Xbox Triangle on PlayStation) = respawn at start of the level
Left face button(X on Xbox Square on PlayStation) = respawn at last activated checkpoint
```
**Camera Movement Behaviour**
While the player is moving have the camera constantly try to center itself vertically so it will naturally oppose the player's vertical input and reduce sensitivity.
If the player is stopped or nearly stopped allow free control of vertical movement so they can spectate and look around the level.

**Comment by cr4yz** [comment]
Got this finished, will be doing a few more tweaks to clean up camera motion when playing with controller.  

I've hard-coded a controller sensitivity for now so it _should_ feel alright without having to go through Steam's controller config
