### ISSUE TITLE
uf_prop transparency

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#38]
when I tie uf_prop to a mesh and set it to camera fade, it fades out when my character is touching it and the camera is not obstructed by it
![image](https://user-images.githubusercontent.com/11905265/155391900-7b906dea-c6d0-47e1-9b62-9d03b0b09f8f.png)

**Comment by cr4yz** [comment]
Should be fixed!

**Comment by youhavehowie** [comment]
awesome!
