### ISSUE TITLE
Clamp Camera Pitch

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#42]
Was trying to figure out how to do this on my own but I'm not smart enough to figure out how to define rotations :P

basically just want to avoid ugly camera clipping like this
![image](https://user-images.githubusercontent.com/11905265/160645609-b342ce10-eab8-4c8d-a7c1-87372c3f4e34.png)

I think a min pitch for the targetRot set to -35f looks pretty good, so this is as close as we get to the bottom wheel
![image](https://user-images.githubusercontent.com/11905265/160646579-1f125fc2-56e2-4a9e-b8ab-a6f5ce6eb718.png)

**Comment by cr4yz** [comment]
Done!
