### ISSUE TITLE
Character skin isn't applied on menus/ragdolls

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-unicycle-frenzy#49]
The player's skin color isn't applied in the menus or to ragdolls

I'm using the blue skin. it works when you're alive:
![image](https://user-images.githubusercontent.com/39461072/170801687-a63f8cef-bfe3-41e2-96da-1e3130463225.png)

ragdoll uses default skin color:
![image](https://user-images.githubusercontent.com/39461072/170801705-588c7838-08fb-40cc-9439-3a8dbb8ddf19.png)

menu uses default skin color:
![image](https://user-images.githubusercontent.com/39461072/170801718-15808fc7-b4e1-4708-b453-85db23de617a.png)

**Comment by cr4yz** [comment]
Fixed, thank you!
