### ISSUE TITLE
Volleyballs in volleyball collecting section of tutorial are physically colliding with player causing them to fall

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#50]
I probably want to rethink this section to mimic how the new F-R-E-N-Z-Y collecting mechanic works but for the time being we should at least get it working so new players can complete the tutorial

https://user-images.githubusercontent.com/11905265/182219391-94179278-3e7e-4edf-b91d-ba21b91702a5.mp4

**Comment by bakscratch** [comment]
Give that a god!

**Comment by youhavehowie** [comment]
awesome, thanks!
