### ISSUE TITLE
Difficulty indicators for level thumbnails

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#52]
I think we should signal how difficult a course is going to be before a player starts a server or votes for a map on the voting screen and I think we can communicate that easily through the thumbnail.

I'm thinking we can either add an easy, intermediate, or expert label, something along the lines of this but something that fits the style better
![image](https://user-images.githubusercontent.com/11905265/189223163-08892883-03cc-4c14-9b45-0eb6564b220a.png)

or a gauge that indicates the difficulty that we put in the corner of every thumbnail
![image](https://user-images.githubusercontent.com/11905265/189223377-6520a54f-40ee-4bcc-acaa-d6fa662eaed0.png)

**Comment by lewisainslie** [comment]
@youhavehowie I've got the assets for this now,

Do you have a 1-6 ranking of each map on difficulty and I can update the assets. 

![image](https://user-images.githubusercontent.com/1823266/189359098-dfecc89b-4e06-45c6-8b6e-8bcb56096193.png)

**Comment by youhavehowie** [comment]
thanks lewis, came out great!
