### ISSUE TITLE
Getting stuck on Angled geometry

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#64]
This is difficult to make happen reliably but you can see a good example of what's happening here. The character comes to a sudden stop when they should continue to roll normally, hard to say but I think it happens more so over the transition of two track pieces.

https://github.com/Facepunch/sbox-unicycle-frenzy/assets/11905265/558af35f-1a52-42cf-966e-41153f123fe9

I think it may also be related to this floating I noticed off of the start checkpoint as well

https://github.com/Facepunch/sbox-unicycle-frenzy/assets/11905265/e7d1248a-ebef-45ce-a5ed-80b379c2fd17

and it definitely seems to happen more so on the downward angles, here the character steps up and down and then gets stuck

https://github.com/Facepunch/sbox-unicycle-frenzy/assets/11905265/2619c708-ab50-4431-b494-6361edb4097c

I set up a scene for testing the issue called angle_testing.scene

**Comment by Metapyziks** [comment]
Added a branch with a tweak that might help, it should sort out the floating at least.

**Comment by Metapyziks** [comment]
Glad it helped a bit, I'll mess around with it more at the weekend. Happy for someone else to give it a shot before then though.

**Comment by Metapyziks** [comment]
Investigating now

![image](https://github.com/Facepunch/sbox-unicycle-frenzy/assets/1110904/8be9e225-e626-45bb-8864-86b7ac476a54)

**Comment by Metapyziks** [comment]
Seems much better if I change the traces to use spheres (with the radius of the tyre), just ironing out the kinks a bit.

**Comment by Metapyziks** [comment]
Pushed to the branch, let me know if that helps @youhavehowie 

I've also added some gizmos to show the ground normals along the path the player took, like the screenshot above.

**Comment by youhavehowie** [comment]
amazing, it feels perfect now! Haven't noticed any sticking/popping whatsoever. Really appreciate the help James, miles better than it was!
