### ISSUE TITLE
Character becomes grounded too soon after jumping on inclines

### ISSUE THREAD

**Issue by youhavehowie** [Facepunch/sbox-unicycle-frenzy#8]
Was playing Louie's new map and noticed at this part where you have to jump across two inclining platforms that my character returned to grounded right after I released jump when trying to jump off the second platform. Is there a way we could make the ground check less sensitive in situations like this so the jump still executes?

https://files.facepunch.com/howie/1b1311b1/s%26box%202021-12-13%2016-17-04.mp4

**Comment by cr4yz** [comment]
Re-opening, I've noticed this a few times recently when jumping while moving fast up a slope

**Comment by cr4yz** [comment]
> Re-opening, I've noticed this a few times recently when jumping while moving fast up a slope

Think I tricked myself, it's just hard to notice jumping while moving up a slope fast because the player is quickly reaching a taller point on the slope and touching the ground anyways.  And I don't think it's been a problem on any maps.
